id: ID6BE99B9
legacy_id: P010668
ocr_import_info:
  bdrc_scan_id: W1KG17578
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T04:27:44'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T09:39:30.430311+00:00'
last_modified: 2022-08-31 17:39:37.799756
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG17578
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG17578
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྟོབས་འཕྲོག་དབང་པོའི་གཏོར་སྐྱོངས་དམ་ཚིག་བསྐང་གསོའི་ངག་འདོན་འགལ་རྐྱེན་དྲི་མ་ཁྲུད་པའི་འཆི་མེད་བདུད་རྩིའི་ཆུ་རྒྱུན།
  author: ས་སྐྱ་ཁྲི་ཆེན ༣༢་ཀུན་དགའ་བློ་གྲོས།
statistics:
  ocr_word_mean_confidence_index: 0.7810137525051524
  ocr_word_median_confidence_index: 0.9100000262260437
quality: null
bases:
  I1KG17940:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17940
      total_pages: 148
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG17940.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.7810137525051524
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
