id: opecha:P010668
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17578
  title: སྟོབས་འཕྲོག་དབང་པོའི་གཏོར་སྐྱོངས་དམ་ཚིག་བསྐང་གསོའི་ངག་འདོན་འགལ་རྐྱེན་དྲི་མ་ཁྲུད་པའི་འཆི་མེད་བདུད་རྩིའི་ཆུ་རྒྱུན།
  volume: ''
  author: ''
